### ISSUE TITLE
Preview error when include tutor and spoor extensions. Authoring tool v0.1.5

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_authoring#1132]
Steps to reproduce:
Clone v0.1.5 of authoring tool
Change version.json so v2.0.8 of the framework would be installed
node install
Start server and build a simple course and include the following extensions: tutor and spoor.

Errors on preview:

```
Running "replace:dist" (replace) task
Warning: Error while processing "courses/570cf99483ba3dd3137745db/570cfb12bf976f1c1470248c/build/imsmanifest.xml" file. Use --force to continue.

Aborted due to warnings.
```

```
error: [12 Apr 2016 14:43:18 +01:00] Error: Command failed: /bin/sh -c grunt server-build:prod --outputdir=courses/570cf99483ba3dd3137745db/570cfb12bf976f1c1470248c/build --theme=adapt-contrib-vanilla --menu=adapt-contrib-boxMenu

error: [12 Apr 2016 14:43:18 +01:00] Error: Command failed: /bin/sh -c grunt server-build:prod --outputdir=courses/570cf99483ba3dd3137745db/570cfb12bf976f1c1470248c/build --theme=adapt-contrib-vanilla --menu=adapt-contrib-boxMenu```

**Comment by dancgray** [comment]
I have not been able to reproduce this issue after upgrading the authoring tool to v0.1.6

**Comment by hmaffin** [comment]
I get it every time. I disabled Tutor but no joy. The only thing that works is deleting the build folder and previewing again. But when I add back in some custom pngs and a folder for my responsive iframe and then a few previews later it breaks again. Will try disabling Spoor now.

**Comment by hmaffin** [comment]
info: [13 Apr 2016 12:00:46 +01:00] Retrieving JSON
info: [13 Apr 2016 12:00:47 +01:00] All assets processed
info: [13 Apr 2016 12:00:47 +01:00] 3.1. Ensuring framework build exists
info: [13 Apr 2016 12:00:47 +01:00] 3.2. Using theme: adapt-contrib-pci
info: [13 Apr 2016 12:00:47 +01:00] 3.3. Using menu: adapt-contrib-finMenu
info: [13 Apr 2016 12:00:47 +01:00] grunt server-build:prod --outputdir=courses\
5614f85c4bd4be5018026e8f\56dee980012883441b702df7\build --theme=adapt-contrib-pc
i --menu=adapt-contrib-finMenu
error: [13 Apr 2016 12:01:07 +01:00] exec error: Error: Command failed: C:\Windo
ws\system32\cmd.exe /s /c "grunt server-build:prod --outputdir=courses\5614f85c4
bd4be5018026e8f\56dee980012883441b702df7\build --theme=adapt-contrib-pci --menu=
adapt-contrib-finMenu"

error: [13 Apr 2016 12:01:07 +01:00] stdout error: Running "server-build:prod" (
server-build) task

Running "_log-vars" task
The following will be included in the build:
- adapt-contrib-pci
- adapt-contrib-finMenu
- adapt-contrib-pageLevelProgress
- adapt-devtools
- adapt-search
- adapt-contrib-bookmarking
- adapt-contrib-resources
- adapt-contrib-assessment
- adapt-contrib-spoor
- adapt-contrib-glossary
- adapt-cheat
- adapt-articleBlockSlider
- adapt-contrib-blank
- adapt-contrib-graphic
- adapt-contrib-text
- adapt-contrib-responsiveIframe
- adapt-tabs
- adapt-contrib-mcq
- adapt-contrib-hotgraphic
- adapt-contrib-media
- adapt-contrib-accordion
- adapt-contrib-textInput
- adapt-contrib-narrative

>> Using source at "C:\Adapt\adapt_authoring\temp\5614f85c4bd4be5018026e8f\adapt
_framework\src\"
>> Building to "courses\5614f85c4bd4be5018026e8f\56dee980012883441b702df7\build\
"
>> Using theme "adapt-contrib-pci"
>> Using menu "adapt-contrib-finMenu"

Running "copy:index" (copy) task
Copied 1 file

Running "copy:courseAssets" (copy) task


Running "copy:courseJson" (copy) task


Running "copy:componentAssets" (copy) task
Created 1 directories, copied 13 files

Running "copy:componentFonts" (copy) task


Running "copy:extensionAssets" (copy) task
Created 1 directories, copied 1 file

Running "copy:extensionFonts" (copy) task


Running "copy:menuAssets" (copy) task


Running "copy:menuFonts" (copy) task


Running "copy:themeAssets" (copy) task
Created 1 directories, copied 12 files

Running "copy:themeFonts" (copy) task
Created 1 directories, copied 4 files

Running "copy:main" (copy) task
Copied 18 files

Running "less:compile" (less) task

Running "handlebars:compile" (handlebars) task
>> 1 file created.

Running "javascript:compile" (javascript) task

Running "replace:dist" (replace) task
Warning: Error while processing "courses/5614f85c4bd4be5018026e8f/56dee980012883
441b702df7/build/imsmanifest.xml" file. Use --force to continue.

Aborted due to warnings.


Execution Time (2016-04-13 11:00:48 UTC)
loading tasks         379ms  █ 2%
copy:componentAssets  238ms  █ 1%
less:compile          982ms  ███ 5%
handlebars:compile    672ms  ██ 3%
javascript:compile    16.4s  ██████████████████████████████████ 85%
Total 19.3s


error: [13 Apr 2016 12:01:07 +01:00] Error: Command failed: C:\Windows\system32\
cmd.exe /s /c "grunt server-build:prod --outputdir=courses\5614f85c4bd4be5018026
e8f\56dee980012883441b702df7\build --theme=adapt-contrib-pci --menu=adapt-contri
b-finMenu"

error: [13 Apr 2016 12:01:07 +01:00] Error: Command failed: C:\Windows\system32\
cmd.exe /s /c "grunt server-build:prod --outputdir=courses\5614f85c4bd4be5018026
e8f\56dee980012883441b702df7\build --theme=adapt-contrib-pci --menu=adapt-contri
b-finMenu"

**Comment by brian-learningpool** [comment]
There is a PR on the framework to fix this.
https://github.com/adaptlearning/adapt_framework/pull/1022

**Comment by brian-learningpool** [comment]
Closing this issue as the framework PR has been merged to `master`.
