### ISSUE TITLE
Sidebar filters functionality

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_authoring#1327]
Just a query about the sidebar filters – is it as designed that they’re all checked by default?

When I first click on _Extensions_, for example, I would’ve expected to be shown the extensions’ configuration.

On sites like Amazon, the filters are all unchecked by default, showing all items. When one is selected the filtering is then started.

**Comment by taylortom** [comment]
I'm in two minds about this.

I felt the original functionality (which was set up as you describe) felt a bit unnatural. *However*, I'm often frustrated at having to turn off all of the filters, rather than simply enabling the one I want.

One solution to this could be to introduce a tabbed layout, with each section in its own tab (obviously quite a bit of work).

If we're to keep the filters, I think we need to look at their presentation/styling, as I think the way we use switches here confuses the situation. If we make it more obvious that the switches are indeed filters, and that to begin with nothing's filtered (somewhat akin to the asset manager), then it makes sense to have them all off by default as before (that said, I don't think the asset manager goes far enough). Also agree with your point re. Amazon, useful as an example.

This may be something to park until the UI rewrite.

**Comment by taylortom** [comment]
The original design intention here is that the 'basic' toggle is on by default, and that all others are off, hiding the more advanced/optional configuration options.
