### ISSUE TITLE
Should be able to force a full rebuild of a course

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_authoring#1497]
When updating a plugin for an existing course it would be nice to have a force-rebuild button that rebuilds all the CSS + JS. At the moment I have to add a random extension and remove it everytime to make the Authoring Tool rebuild fully.

**Comment by taylortom** [comment]
👍  A _slightly_ better to do this is to just go into the theme picker and click save. I've done something like this in the Kineo fork, will dig it out and submit a PR.

However, I think this is only a temporary solution; the real problem here is that the build process is pretty poor. I think we need to get to a place where preview uses an 'instant build', and the full build is only run on download/export. This being said, I don't think this is possible using the current framework set-up (particularly the way we use require).

**Comment by simondate** [comment]
It would be nice if there were some kind of 'developer-mode' that can be enabled for certain accounts (maybe super admins) that have access to advanced features that are only required by developers/system admins.

**Comment by taylortom** [comment]
@simondate I've set up a 'super toolbar' in the Kineo code which adds a toolbar to the top of the main window for super admins only, and can house any kind of functionality. See here for code: https://github.com/cgkineo/adapt_authoring/tree/staging/frontend/src/plugins/superToolbar

I'm not sure how I feel about this kind of thing in the open-source code though, feels a bit hacky.

**Comment by simondate** [comment]
Is there a way to automate this? 

If any version change has occurred rebuild the course?
