### ISSUE TITLE
Filling attribution field from asset manager

### ISSUE THREAD

**Issue by davetaz** [adaptlearning/adapt_authoring#1547]
After extending the asset manager to include an attribution (as well as licence and source) field I'm really lost on how to get this to autofill the attribution field on a graphic component when you select a graphic. 

I'm looking for the behaviour to be that it autofills if there is no value in this field already. 

I've looked in scaffoldAssetView and have a branch with some code in here however I have no idea how I can make this work. 

https://github.com/davetaz/adapt_authoring/blob/assetMetadata/frontend/src/core/scaffold/views/scaffoldAssetView.js

Any help appreciated.

**Comment by taylortom** [comment]
Did you try my suggestion @davetaz?

**Comment by davetaz** [comment]
I hacked around with it for a long time but couldn't get the the point of actually assigning the value as the _graphic object is undefined at the point in the routine you pointed me at. Either I'm being stupid or it is set/reset elsewhere. The only way I could assign it was with a setTimeout which then ensures the _graphic object is created, this is a hack and I didn't like it.

**Comment by taylortom** [comment]
What about this: https://github.com/cgkineo/adapt_authoring/blob/96f976e9afd5c5e69792f192ec989678c35a081a/frontend/src/plugins/graphicAttribute/index.js

That got pretty close in my tests, from what I remember (haven't looked at it since I set it up). Should just be a case of getting the right value [here](https://github.com/cgkineo/adapt_authoring/blob/96f976e9afd5c5e69792f192ec989678c35a081a/frontend/src/plugins/graphicAttribute/index.js#L16), and maybe adding a conditional [around here somewhere](https://github.com/cgkineo/adapt_authoring/blob/96f976e9afd5c5e69792f192ec989678c35a081a/frontend/src/plugins/graphicAttribute/index.js#L5) to only listening when on a graphic.

**Comment by davetaz** [comment]
oh hang on, i think i missed a message from you on gitter
