### ISSUE TITLE
Preview Popup allow UX

### ISSUE THREAD

**Issue by canstudios-louisem** [adaptlearning/adapt_authoring#1636]
The first time a user tries to launch a preview most modern browsers block it as a "popup".

That does not lead to a good user experience the first time someone uses adapt, espeically If the user does not notice the popup warning which is easily missed on Chrome as it just seems broken.

**Comment by taylortom** [comment]
There are two possible options (that I can see) here:
1. Load the preview in a modal. I don't like this solution personally, as it interferes with the user workflow.
2. We change how we call `window.open` to allow us to work around the popup blockers.
  1. Call `window.open('')` in the original event handler. We'll probably need some kind of loading page here so it doesn't look broken, so may need to add a new route instead of passing ''.
  2. Update the href when the preview's ready

**Comment by canstudios-louisem** [comment]
As far as I can infer from research the issue is caused because the browser can't link you clicking the button and the window being opened. 

This is normally caused by there being an asynchronous event between the two "events".

I prefer the second option as well as to most users there would be no noticeable change.

**Comment by taylortom** [comment]
This should fix the issue: https://github.com/adaptlearning/adapt_authoring/compare/thebigbugfix/refactor...issue/1636?expand=1

**Comment by canstudios-louisem** [comment]
I have created a PR #1640

**Comment by canstudios-nicolaw** [comment]
@taylortom Can this issue be closed now or are they closed on release?

**Comment by taylortom** [comment]
Can close it manually, but will close as soon as the commits are merged into master
