### ISSUE TITLE
Rapid Author: Single Page Course Alignment

### ISSUE THREAD

**Issue by pgarrighi** [adaptlearning/adapt_authoring#1641]
If a single page course is created it is by default left aligned when previewed or run.  Can an option be created in Rapid Author to centre this page please

**Comment by taylortom** [comment]
@pgarrighi this is something that's determined by the framework theme that's selected, rather than the authoring tool itself.

I'd suggest maybe bringing this up in the [theming Gitter room](https://gitter.im/adaptlearning/theming), or on the [adapt-contrib-vanilla repository](https://github.com/adaptlearning/adapt-contrib-vanilla).
