### ISSUE TITLE
Project specific id's

### ISSUE THREAD

**Issue by canstudios-louisem** [adaptlearning/adapt_authoring#1752]
When copying a course any components or styling that use specific id's break

## Affected Area
Course Copying

## Requested Feature
No longer use the _id on ABC's but a _courseId that is not regenerated when the course is copied 

## Additional Information
We have written a detailed proposal on how we would like to tackle this https://docs.google.com/document/d/17JNGj6szijXtxHcFehNLXfi18D2jO4DHcMHeXuf2c5g/edit?usp=sharing

**Comment by Janooba** [comment]
I'd like to add my support for this feature, as it would be extremely important for our team. We currently do not use the authoring tool because of this alone. The ID's are not human-readable and once exported, manually editing the course (as its often required for us) becomes nearly impossible.

If I may make a suggestion, I'd like the generated _id's to follow a similar _readable_ standard to the following.

>The goal of this naming convention is to meet the following criteria. It must be:
>- Concise (As small and easy to type as possible)
>- Readable (Should be distinct and simple to read)
>- Self-documenting (Should trace back exactly where this element is located within the structure)
```
Content Object: [#]
Article: [A-Z]
_ (Underscore)
Block: [#]
Component: [a|b]
```

> Examples:
> - 01B_16a
> - 02A_04b

Our team has been using this structure to manually develop Adapt courses for a while now with great success.

Cheers!
