### ISSUE TITLE
Unit tests are very slow to run

### ISSUE THREAD

**Issue by canstudios-louisem** [adaptlearning/adapt_authoring#1761]
## Expected Behaviour
Tests should run quickly this allows developers to run them often as they work

## Actual Behaviour
Due to the fact it installs the framework multiple times during the tests, they are very slow to run.

## Versions
  - Authoring Tool Version: 0.4.0

**Comment by taylortom** [comment]
Agree with this, but could be tricky to get around it without falsifying the tests -- the majority of the time is spent setting up the environment. 

We could maybe look at reusing the env, and just make sure we start with a clean db etc.

**Comment by canstudios-louisem** [comment]
I was thinking about caching the framework for tests so we rebuild a tenant but from a cache.

**Comment by taylortom** [comment]
This could work, I had it in my mind that the tenant manager tests installed a new master tenant, but this isn't the case, so that test is very quick. 

The `installHelpers.installFramework` code already handles existing framework clones by just doing an update, so the easiest thing to do would be to copy the test framework into the right dir prior.

**Comment by benhalverson** [comment]
@taylortom @canstudios-louisem When I was running the tests I eventually got a github rate limiting error. Can't the testing be done without making actual network requests.

**Comment by taylortom** [comment]
@benhalverson unfortunately not the way they work currently, due to the way we check for new versions. This is something that needs fixing.
