### ISSUE TITLE
Help Text Doesn't Show for List Fields

### ISSUE THREAD

**Issue by canstudios-matth** [adaptlearning/adapt_authoring#1772]
## Expected Behaviour
If an extension, plugin, etc has a help field in its schema for a list field, this should be displayed on the front end.

## Actual Behaviour
The help text doesn't show.

## Steps to Reproduce
1. Add and enable a plugin that has a list field
1. Edit the settings of the above plugin and navigate to the list field
1. Note that help text isn't shown for this field

## Versions
  - Authoring Tool Version: v0.4.0
  - Framework Version: v2.2.2

**Comment by tomgreenfield** [comment]
Could you provide a snippet of your schema, @canstudios-matth?

**Comment by canstudios-matth** [comment]
Hi Tom,
It isn't a plugin-specific issue; the help text simply isn't being sent to the front-end for rendering. Please see the PR for reference - it should help clarify exactly what the issue is.

**Comment by tomgreenfield** [comment]
Only checking because list fields in this [format](https://github.com/adaptlearning/adapt_authoring/blob/master/plugins/content/contentobject/model.schema#L81-L89) are able to render help text, in case you wanted an quick ‘fix’.

I agree the scaffold is a right pain and inconsistent with properties it passes through; I've made substantial headway with refactoring it to alleviate these issues.
