### ISSUE TITLE
Escape directory paths in installHelpers.js

### ISSUE THREAD

**Issue by MarkWestside** [adaptlearning/adapt_authoring#1797]
# Failed to create master tenant

Hello everyone,

I am trying to install Adapt and can’t figure out the problem. Node and Mongo are working for me on other projects.

When I run the install with the same settings again, I get the following message:
`Tenant 'master' already exists, automatic install cannot continue.`
So is there a problem with setting up the database?

Could someone help me with the installation?

Best regards

## Expected Behaviour
Install without errors

## Actual Behaviour
After setting the display name for the tenant during the initial installation, the following error occurs:
`ERROR: fatal: Too many arguments.`

## Steps to Reproduce
1. Installed Node.js, MongoDB, FFmpeg and Grunt
2. Cloned Adapt authoring tool
3. Installed required packages
4. Ran install script
5. Used default settings except for FFmpeg
6. Entered display name for tenant
7. `ERROR: fatal: Too many arguments. (usage: git clone [<options>] [--] <repo> [<dir>])`
8. `Failed to create master tenant. Please check the console output.`

## Versions
  - Authoring Tool Version: 0.4.0
  - Operating System: macOS 10.13.1
  - Node.js: 6.11.3
  - MongoDB: 3.4.10
  - FFmpeg: 3.4
  - Grunt: 0.4.5
  - Grunt CLI: 1.2.0
  - Git: 2.13.6

**Comment by moderatemisbehaviour** [comment]
### Workaround
Hi @MarkWestside, the problem for me was that the path to the directory I had done the original clone of 
this repo in had a space in it, e.g. `/home/dan/The Laboratory/adapt_authoring`. Clone it somewhere else and re-try the installation, e.g. `/home/dan/adapt_authoring`.

### More detail about the problem
This can be fixed by escaping the path. The [git clone command](https://github.com/adaptlearning/adapt_authoring/blob/9314ca37a58d3dc314b376e6740a6493620e7ba2/lib/installHelpers.js#L341) in `installHelpers.js` passes an argument for the directory which for me was `/home/dan/The Laboratory/adapt_authoring/temp/5a31a1543aebf8a1647ef504/adapt_framework`. The space in `The Laboratory` makes the git executable think that is the beginning of another argument, which is invalid syntax. I'm sure there is an NPM package that will escape paths in a cross-platform manner, I may create a PR at the weekend if I have time but its unlikely.

**Comment by MarkWestside** [comment]
Great, that did the job. I did had a space in folder.

Thanks a lot, moderatemisbehaviour!

**Comment by moderatemisbehaviour** [comment]
@taylortom may I ask why this has been closed? The problem still exists.

**Comment by taylortom** [comment]
Apologies, interpretated this as a non-at issue.

**Comment by moderatemisbehaviour** [comment]
@taylortom nice one, thanks for the fix :)
