### ISSUE TITLE
Ability to Set a Default View and/or Default to "Recent"

### ISSUE THREAD

**Issue by trueschool** [adaptlearning/adapt_authoring#1857]
# Course Ordering -- Preference for "Recent" courses
I notice that the authoring environment's home screen seems to default to ordering courses by the time they were created[?] or maybe alphabetically[?] 

I usually want to see the courses I'm currently working on first, so defaulting to "Recent" first would be my preferred default. Of course, other people may disagree, so it would be awesome to have a toggle or preference that allows us to set our own preferred view. 

## Steps to Reproduce
1. Go to authoring environment
1. See how courses are ordered
1. Scratch head and wonder why...

**Comment by taylortom** [comment]
Related to #1337

**Comment by lc-thomasberger** [comment]
The odd (alphabetic) sorting may be caused by MongoDB not supporting case-insensitive indexes before Version 3.4. Sorting is ordered by: 0 - 9, A - Z, a - z.
https://docs.mongodb.com/manual/core/index-case-insensitive/

To fix this for users with MongoDB lower then 3.4 we would need a sort index entry that is set to lowercase by JavaScript.
