### ISSUE TITLE
Add support for importing a course with an earlier framework version

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adaptlearning/adapt_authoring#2288]
## Affected Area
If I have made a course with an earlier version of the framework I should be able to import it into my current authoring tool. At the moment if I try to import a v2 framework course into an authoring tool that is running v4 framework then the import will fail.

## Requested Feature
In this case I should be guided through the process of importing my v2 course. Exact form of guidance is tbc but could be modals or additional import form fields.

Guidance will be a case of informing me that:
- this course was originally built on an older framework
- subsequently there may be some breakage and the course should be tested after import
- (possibly) switch the theme to v4 vanilla so that there is at least a basic theme that works
- check all course plugins are compatible with v4 framework. There are a few possibilities:
    - The plugins are compatible but need to be installed - install as part of normal import
    - The plugin that is on the course is not compatible with v4 but a newer version of that plugin is already installed - give warning
    - The plugin that is on the course is not compatible with v4, a newer version exists but is not installed - this is possibly not mvp, need to look into effort estimate for this
    - The plugin is not compatible with v4 and no newer versions of it exist - prevent import 

## Use Case
There are many users who would like to use v4 framework in the authoring tool but also need to maintain older courses written in v2. This process will help them import v2 courses into a v4 authoring tool for easier maintenance. 

## Current Workaround
Currently it is not possible to import a v2 course into the v4 authoring tool

**Comment by canstudios-nicolaw** [comment]
@dancgray This is along the lines of what was discussed in the multiple framework support call. It's all quite rough at the moment and details may change when I start work on this. 

I'm currently planning to work on this after theme editing

**Comment by Rahulc24** [comment]
Hi,

I'm currently trying to make some textual updates to a Adapt course that was developed by someone else a few years ago. Unfortunately, I do not have access to the original Adapt authoring instance used to create it. All I have are a few ZIP files, which I believe are the source packages. I attempted to import these ZIP files into my current Adapt authoring tool instance but encountered the following error:
“This course can't be imported.”
(Screenshot attached)

After investigating, it seems that the original course may have been built using custom or local plugins that are no longer available in the public Adapt plugin library. I suspect this is causing compatibility issues, especially since the framework and plugins used at that time appear to be outdated compared to the current Adapt version.

I also searched the Adapt public plugin library for the missing plugins referenced in the course files but was unable to find them.

Could you please advise on:

Whether there’s a workaround to import such older courses?
Please suggest ways to solve this.
Please note that I’ve only recently started using the Adapt authoring tool- just a few days ago- so I’m still learning the platform. I would really appreciate your guidance on how best to proceed. I would really appreciate your guidance at the earliest, as I’m on a tight deadline to update and redeploy this course.

<img width="947" height="460" alt="Image" src="https://github.com/user-attachments/assets/72196261-d7e4-4a8a-8c14-c7b7e61c648b" />
<img width="1321" height="855" alt="Image" src="https://github.com/user-attachments/assets/d6ddf28d-8436-4ab5-b96d-3be10cae25ac" />
