### ISSUE TITLE
Theme picker: Selected preset dropdown keeps showing "No preset"

### ISSUE THREAD

**Issue by canstudios-kent** [adaptlearning/adapt_authoring#2379]
## Expected Behaviour
When entering Theme picker area, it should show the currently applied base theme and (if one exists) preset.

## Actual Behaviour
The preset dropdown will always display "No preset" instead of the applied preset when entering the Theme picker area.

## Steps to Reproduce
1. In a course, navigate to Theme picker.
1. Select a theme and preset. Click Save.
1. Preview the course. Check preset is applied.
1. Return back to Theme picker. Notice that "No preset" is being shown.

## Versions
  - Authoring Tool Version: 0.8.1; 0.9.0
  - Framework Version:

**Comment by canstudios-nicolaw** [comment]
Currently, when a preset is selected, the variables associated with the preset are saved to the course but the preset itself is not.

ie. the course might contain something like 

```
"themeVariables": {
        "_colors": {
            "highlight": "#d829f1",
            "image-outline": "#505050"
        }
    }
```

This means that when the theme editing page is re-opened, there isn't a way for it to determine the preset that was last chosen. 

We would need to save "lastSelectedPresetId" or similar to the course in order to display this information when the page is re-opened. I think this needs to be discussed before I go ahead and make changes.

@tomgreenfield @dancgray

**Comment by canstudios-nicolaw** [comment]
Any more thoughts on this? I can work on it this afternoon if we have decided on an approach

**Comment by tomgreenfield** [comment]
Happy for you to proceed if there are no objections from others.
