### ISSUE TITLE
`_globals._extensions` UI

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_authoring#2693]
In addition to https://github.com/adaptlearning/adapt_authoring/issues/2691, the UI for child nodes are incorrectly displayed in the UI. `_components` and `_extensions` are nested under 'Accessibility' (`_accessibility`) rather than within their own nodes.

**Comment by simondate** [comment]
Built upon @taylortom 's PR to add titles to the Components and Extensions attributes #2692 

Note - I've hardcoded the titles. I tried to use `origin.l10n.t('app.components')` but it didn't compile, I guess this call is happening too late in the build cycle. I noticed the `es.json` file didn't have different terms for Components and Extensions and since this is meant to be a quick final fix for the `0.X.X` versions I figured this will be acceptable
