### ISSUE TITLE
Use hashed filenames on output

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_authoring#602]
There is some code in the output which reconciles the hashed filename with the filename uploaded by the user.  I propose that we should forget reconciling this and instead use the hashed filename.  This has an impact in terms of readability, however it solves some techical issues.
- No more conflicts with myFile.png and myFile.PNG.
- Less processing required so in theory a faster build time.
- No issues with unusable filenames, e.g. filenames with spaces, etc.

**Comment by LukaszGrela** [comment]
-1, if I may:) 
All those issues could be resolved at the asset manager when asset is being added e.g. 
- letting user know that file name is already in use (using windows strategy so myFile.png and myFile.PNG will be treated the same)
- unusable names made usable automatically (e..g with underscores) or prompt user to fix it,

Personally I would like to have it readable than hashed:)

**Comment by dennis-learningpool** [comment]
@LukaszGrela - The main problem here is with published files, not with the upload/storing of files. I'm in favour of hashing, mainly because I believe the output of the authoring tool should be treated as a published file - not something that should be hand-edited by an end user.

I'm also not in favour of making it a Course Creator's responsibility to manage conflicts in filenames - I think asset uploading should be (reasonably) smooth. I think it would be quite annoying to be prompted to rename uploaded files, even with a system suggested alternative name.

There is an item on the roadmap to support an uncompressed publish with the intention of supporting easier hand-editing, but, again, the problem manifests itself at publish time, rather than asset creation time. At that point, I think a simple underscore for space replacement, plus appending a count to duplicate filenames should suffice (i.e. myFile.png, myFile(1).png,myFile(3).png).

**Comment by taylortom** [comment]
+1 for @dennis-learningpool's suggestions.

I'm coming round to the idea of *not* having human-readable IDs, but I think we need to have something in place which allows users to very quickly and easily determine what the IDs of elements are both inside and outside of the tool.

Here's a design review scenario use case:

**Scenario**: Previewing the course in browser, typo spotted in a component body text.
**Manual workflow**: Inspect the element, grab its ID, and do a *find* in the components.json.
**Builder workflow**: Have to work out which page/article/block the component's in using the page titles etc. and navigate through the hierarchy manually to get to it.

**Comment by taylortom** [comment]
Closing, as we now use hashed filenames.
