### ISSUE TITLE
Hotgraphic completion in page level progress

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt_authoring#728]
I have page level progress turned off on my hotgraphic and when i scroll down my page without using the hotgraphic it shows as completed in my progress bar at the top of the page, however if I go back to the menu and look at the progress bar for the page in question, it's showing as around 90% complete not 100%.

If I then go back into the page (with top bar progress still showing complete) and then use the hotgraphic, return to the menu, THEN the bar on the boxmenu shows as complete for that page.

Not sure if this is just me or is replicable, i will try and delete and readd the hotgraphic to check, or start a new project to test.

**Comment by brian-learningpool** [comment]
I'm not sure there is a bug here.

Although it does have a progress bar, the Box Menu is completely independent from Page Level Progress.  If you have disabled Page Level Progress on a specific component it will have no effect on the progress bar pulled through on the Box Menu.

**Comment by hmaffin** [comment]
Hmmmm so what is telling the Box menu bar that I haven't finished the page?

**Comment by brian-learningpool** [comment]
In the scenario you've given it would be the hotgraphic.  You said on the first pass you didn't complete it but the page level progress goes to 100% while the progress bar on the Box Menu does not. 

Version 1.1 of the framework doesn't support optional components for completion.  This is coming with version 2.0.  So, even though you've turned of Page Level Progress for the hotgraphic, that hotgraphic still must be completed in order to complete the course or get 100% of the page.
