### ISSUE TITLE
Ability to have custom component GUIs in the editor

### ISSUE THREAD

**Issue by dennis-learningpool** [adaptlearning/adapt_authoring#758]
For example, being able to drag and drop hotgraphic pins within my selected image.

**Comment by simondate** [comment]
Hi, has there been any more progress on this?

**Comment by taylortom** [comment]
@simondate this isn't something that's been picked up by any of the core team, it is something that's requested quite frequently by the community though.

**Comment by simondate** [comment]
Thanks @taylortom , do you have any estimate of how long it would take to implement? From what I understand it requires a custom Modal like the ones used [here](https://github.com/adaptlearning/adapt_authoring/blob/bbee5b95e34a69c47ec9c6613ce2d21882927599/frontend/src/core/scaffold/views/scaffoldAssetView.js#L334-L338). Is there any documentation of how to create these?

**Comment by taylortom** [comment]
I think the key feature here is to be able to add custom editors as part of the plugin code/package; the hot graphic input type for example, isn't something we'd want in the core code, as it's specific only to hot graphics.

No idea how long something like this would take, but the bulk of the time would likely be spent writing the interfacing code in the core.

**Comment by simondate** [comment]
Why wouldn't you want a modification like this in core? Hot graphic is a core component that is bundled with the AT, surely any modification to make it easier to use fits within the Adapt vision.

I've seen this feature been implemented in non-core versions of the Authoring Tool so I'm sure it's possible, fairly easy to do.

**Comment by simondate** [comment]
Sorry, I appreciate that I'm raising a specific issue where this issue was meant to be a broader change. Happy to create a new ticket for this if you think it's applicable.

**Comment by taylortom** [comment]
I agree that we should add (and support) the input as the open-source project, but I don't agree that it belongs in core; the aim is for the core code to remain as un-opinionated as possible, hence why there's a plugin architecture in place. 

What happens if we drop support for hot graphic in the future, or equally, change the type of input that should be used to define the pin placement? All of the input types we support in the core are very generic, and useful to a wide variety of plugins; it's likely that the hot graphic pin input would be so specific to the hot graphic as to be useless for any other plugin.

To me, it makes most sense for a custom input to belong with the plugin's code (along with the schema, which defines the input types the plugin uses).

**Comment by taylortom** [comment]
Closing this, as it's already possible to create custom input fields (provided they output data as expected by the schema).
