### ISSUE TITLE
Need to replace hard-coded error messages with translated ones

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#842]
origin().polyglot()

**Comment by samumist** [comment]
@taylortom I'm working on a Chinese translation of the `en-applicaiton.json` and the `*.model.shema` from the FW (V4). Then I found some hard-coded strings, such as 'Dashboard - viewing my courses' etc. 

I figure it is pretty hard to identify those hard-coded strings since there're all plain English:-) But for my process it is much easier to pick them out.

I'm thinking of sending in a PR for the hard-coded strings and the `en-application.json`. Please advice if there's something else I need to do regarding this.

**Comment by tomgreenfield** [comment]
Hi @samumist, I'd recommend holding fire until the next release before putting any work into this.; you may find it has already been resolved:

![dashboard](https://user-images.githubusercontent.com/922987/54344775-8cc03e00-4639-11e9-9d8b-92890b1810ed.jpg)

**Comment by samumist** [comment]
thanks @tomgreenfield 
looking forward to the next release:-)

**Comment by canstudios-nicolaw** [comment]
@adaptlearning/framework-push I think this could be a candidate for fixing in a bug patch (if it's not fixed already)
