### ISSUE TITLE
Upgrade to 0.1.2 (partially) fails on Win8.1

### ISSUE THREAD

**Issue by danjah** [adaptlearning/adapt_authoring#878]
I've deleted `node_modules`, run `npm install --production` and that all worked fine, but the last command `node upgrade` throws an error, here's the output from the `node upgrade` command: https://gist.github.com/danjah/c99d5134fa159dd11e4d

If I then run the same `node upgrade` command a second time, everything looks upgraded: https://gist.github.com/danjah/cf1d013304c23030a9b0

**Comment by brian-learningpool** [comment]
Thanks for reporting this.  It looks like some kind of a permissions error.  Can you let me know if you've been working off the `master` or `develop` branch previously?

To verify you're plugins are up to date can you go into the Plugin Management screen, and under Extensions and Component click on 'Check for updates' on each row.  It may take a little while but since it looks like the upgrade partially failed on upgrading the plugins it's best to check that the version of your plugins matches the version compatible with the version 2 of the framework.

**Comment by danjah** [comment]
No probs, at first myself and my colleague were working off `master` but experienced a few teething problems related to this issue, or some other dependencies failing. I got the sense that it was a permissions issue, we tried explicitly using admin privs Bash (but we do by default anyway) to no avail. `develop` seemed to work just fine, but I switched back to `master` for the upgrade today.

**Comment by taylortom** [comment]
That's a weird one. Seems to be failing at the `adapt install` of the framework. Does this work for you if you upgrade manually (i.e. switching to develop or similar)?

**Comment by danjah** [comment]
I'll recap the oddities when trying out the AT between about a year ago and today, but to honest we thought it was our own setup more than anything! We encountered install issues that related to `node -v` being stuck on an incorrect version until we got nvm to work (node needed to be uninstalled/removed from PATH/etc) that could have been system legacy issues - I've had node installed and being upgraded for some time now. That resolved, we then had a few issues with `-g` flags somehow not installing dependencies globally - that resolved, and then we had mixups on build process as I mentioned to you on gitter @taylortom (rub/grunt/gulp) - but that resolved too, and now also Brian's note to run `grunt build:prod` after [switching branches] (https://github.com/adaptlearning/adapt_authoring/issues/879)... makes sense, and just wasn't a step we were taking!

I'll continue to post any installation woes, as I have been doing for the Vagrant branch, but hopefully they're a thing of the past!
