### ISSUE TITLE
Add requireRebuild to properties.schema

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#885]
There are a number of cases in which a changing a config option in a course requires a complete rebuild. This results in the user having to manually reselect a theme or menu before previewing.

Suggest that we add an option to the schemas which allows a dev to specify whether to force a rebuild upon next publish.

Another option is to add a watch to the grunt process, which will detect any changes and run the relevant tasks.

**Comment by brian-learningpool** [comment]
The touch-points I can think of are:
* selection of a theme
* selection of a menu
* editing of course custom CSS/LESS

Are there any others?  What config options were you thinking on?

Right now there is a 'rebuildCourse' event, which handles this by writing a file to the filesystem.  It works (generally) but seems a bit clunky to me, and hasn't been really looked at since the original prototype, so I am up for revisiting this.

**Comment by markl55** [comment]
It would be nice if there was also an option in the builder to force a rebuild anyway, like a checkbox on the preview -or- another button called rebuild/publish.

**Comment by taylortom** [comment]
Would be good to revisit this in conjunction with #1358.
