### ISSUE TITLE
Localise all references to 'Adapt Builder'

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_authoring#955]
There are still quite a few hard-coded references to Builder which need to be sorted.

One of the slightly tricker bits is the index.hbs which doesn't have access to the frontend Handlebars helpers, so can't use `{{ t EN_JSON_KEY }}`. 

There still seems to be a fair amount of confusion around the Adapt authoring tool/Adapt builder -- removing all references here will at least help with consistency.

**Comment by brian-learningpool** [comment]
Also, the wiki documentation seems to mention Adapt Origin.

**Comment by chucklorenz** [comment]
Having just completed some documentation work, I was reminded how easily new users can be confused. Thought I'd push for earlier action on this issue.

In the framework wiki, "authoring tool" is used almost exclusively. In the authoring tool wiki, "authoring tool" appears to dominate, but "Origin" (not used to reference the code object) still makes a significant appearance. And in the tool itself, "Builder" is used almost exclusively. 

The authoring tool wiki can be "cleaned up" fairly easily; however, references to the code object Origin must remain. This is unlikely to cause confusion unless a company were to name their version of the authoring tool "Adapt Origin". References to AdaptBuilder are few and very likely unnecessary.

The authoring tool itself (master) uses the phrase "Adapt Builder" approximately 20 times in significant log strings and on the user interface. Confusion between LearningPool's brand "Adapt Builder" and the community version of the authoring tool should be expected until these occurrences can be significantly reduced or eliminated. 

Instead of waiting until localisation can be achieved, can hard-coded references to "Builder" be changed to "Authoring Tool"? This would be very easy to achieve.

**Comment by taylortom** [comment]
Considerable progress has been made here: https://github.com/adaptlearning/adapt_authoring/tree/issue/955 (including temporary replacement of hard-coded values)

**Comment by chucklorenz** [comment]
Thanks, Tom. Sorry I didn't look first for a matching branch.

**Comment by taylortom** [comment]
To add to the discussion: I found the use of Origin as both the front-end *and* back-end components slightly confusing; using different names may help to mentally separate the two (not a big issue for me, but a nice-to-have).

We may also want to consider renaming the `frontend/src/adaptbuilder` folder

**Comment by taylortom** [comment]
Majority of this is done, so moving to backlog for now

**Comment by taylortom** [comment]
Done
