### ISSUE TITLE
Documentation has become out of sync

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_authoring#974]
The README.md is probably the best place to go for installation instructions.

The wiki refers to Node v0.10.33.  Should this page be removed or updated to point back to README.md?  README-windows.md can probably be removed.

As an enhancement it would be worthwhile including a table which lists the required versions of various software.

@chucklorenz, it would be good to get your thoughts on this.

**Comment by chucklorenz** [comment]
I don't believe the README is best  place to go for installation instructions. Installation instructions are too long for a single page. There are (and probably will be for some time) a variety of system configurations that need to be addressed. Forum posters continue to complain about installation of prerequisites/dependencies. A README really shouldn't be expected to address this, yet for the sake of adoption we should be doing it. A README needs to provide quick access to other information, too: contact info, how to contribute, etc.

I recommend the model used with the framework: a README.md, an INSTALL.md, and the wiki --all coordinated. 
- the wiki continues to be the place for the most complete instructions about installation.
- the INSTALL.md remains with the source code and provides instructions of reasonable length and depth targeting professionals in technology. It provides a link to the fuller instructions in the wiki.
- the README.md acts as a landing page: it "sells" the code, and provides links to further action such as installation, contributing, reporting bugs, or contacting the organization for other reasons.

Why I like this set up:
- Currently, there are three entry points into Adapt World: the community site, framework repo, and authoring tool repo. Documentation will continue to be housed in the wikis for the foreseeable future. Each of these needs to make it easy for new adoptees to access available information. If the first thing someone sees (the README) addresses installation, they can easily think they have located all the documentation that they need.
- It is to our advantage to train people to rely on the wiki for information, rather than repeatedly asking the same questions in the forums. We can start that early by sending them to the wiki for install instructions.
- Many repos don't use the wiki, so many people don't check to see what's there. Many e-learning professionals are new to Github; we shouldn't expect that they'll find the wiki button and understand how it could help them with installation. We need to push them there.
- As an OS community, we should expect that community members can easily contribute to documentation, including install instructions. While I'm very comfortable with anyone _adding_ to installation documentation in the wiki, I'm not comfortable with just anyone changing the instructions inside the repo (README and INSTALL).
- Some people feel that install instructions must travel with source code. I am not one of them. I think a link in a README to instructions housed on the wiki is adequate. After all, neither the framework nor the authoring tool can be installed without access to the internet. To meet the concerns of those who disagree with me, we include INSTALL.md with instructions. These instructions are restricted to installing on the most common system configurations, but likewise link to the fuller instructions in the wiki.
- Once these three pieces are in place, the only link to instructions that gets passed around is the one to the wiki, since we no longer have documentation in competition with itself.

(Sidebar: I did not move to implement this earlier because the focus of documentation was on the framework, and I was still easing my way into the organization.)

**Comment by ryangadams** [comment]
I agree that the wiki is the place to put detailed and specific information for the various configurations the authoring tool will be installed on. I am of the opinion that installation instructions are source code, should be executable (i.e. an install script) and should be versioned with the application itself.  If the instructions are too long for a single web page then they're too long and should be reduced/automated. So my opinion would be that the INSTALL.md file should be the main page for installation instructions (linked to from the wiki, github does nice markdown previews) with detailed exceptions or explanations put on the wiki.

There's a wider discussion about installation though, which might be appropriate to begin here (and move to gitter/community when appropriate). There are (I believe) 3 primary installation use cases.

1. A sysadmin installing on a server
2. A developer installing locally for development
3. An end user installing on their local machine for content development

As I recall, we explicitly ruled out 3 as an objective early in development, though there's no reason why it couldn't be done. I believe 2 is best achieved by using vagrant, since that gives us a consistent development environment that can be easily scripted (leaving a link to vagrantup.com for the vagrant installation).  Use case 1 can likely be achieved via converting the vagrant scripts into server release scripts (perhaps using chef or puppet).

**Comment by chucklorenz** [comment]
I have created draft documentation with the assumption that there are two methods for installing the authoring tool:
- manually
- with Vagrant

Currently manual installation is described by a detailed set of instructions ([Installing-Adapt-Origin](https://github.com/adaptlearning/adapt_authoring/wiki/Installing-Adapt-Origin)) intended for less-technical user and a more succinct set ([Developer's-Install](https://github.com/adaptlearning/adapt_authoring/wiki/Developer's-Install)) for those proficient with installing node apps.

I'm proposing the following changes to the authoring tool repo:
- revised [README.md](https://github.com/chucklorenz/demo-wiki/wiki/README:-Draft) (to mirror the framework [README](https://github.com/adaptlearning/adapt_framework/blob/master/README.md))
- new [INSTALL.md](https://github.com/chucklorenz/demo-wiki/wiki/INSTALL:-Draft) (based on [Developers-Install](https://github.com/adaptlearning/adapt_authoring/wiki/Developer's-Install) and to replace the install instructions to be eliminated from the README)

I'm proposing changes to pages in the authoring tool wiki:
- new: [Installing-the-Authoring-Tool](https://github.com/chucklorenz/demo-wiki/wiki/Installing-the-Authoring-Tool:-Draft)
- new: [Install-with-Vagrant](https://github.com/chucklorenz/demo-wiki/wiki/Install-with-Vagrant)
- renamed: [Installing-Adapt-Origin](https://github.com/adaptlearning/adapt_authoring/wiki/Installing-Adapt-Origin) (renamed to Install-Manually)
- deleted: [Developers-Install](https://github.com/adaptlearning/adapt_authoring/wiki/Developer's-Install) (existing references to be linked to [INSTALL.md](https://github.com/chucklorenz/demo-wiki/wiki/INSTALL:-Draft))

I'm proposing changes to the structure of the authoring tool wiki:
- [Wiki home page](https://github.com/chucklorenz/demo-wiki/wiki/Authoring-Tool-Wiki-Home) links to [Installing-the-Authoring-Tool](https://github.com/chucklorenz/demo-wiki/wiki/Installing-the-Authoring-Tool:-Draft). 
- The [Installing-the-Authoring-Tool](https://github.com/chucklorenz/demo-wiki/wiki/Installing-the-Authoring-Tool:-Draft) page lists the methods of installation and provides links to instructions ([Install-with-Vagrant](https://github.com/chucklorenz/demo-wiki/wiki/Install-with-Vagrant), [Install-Manually](https://github.com/adaptlearning/adapt_authoring/wiki/Installing-Adapt-Origin), and [INSTALL.md](https://github.com/chucklorenz/demo-wiki/wiki/INSTALL:-Draft)). It allows for additional methods to be added when they are developed.

The goals of these proposals include:
- pushing most users to the wiki for their install instructions
- helping users to decide which install method to use
- providing install methods/documentation accessible (in some degree) to non-technical professionals.

Please review for accuracy (does git need to be installed before running "vagrant up"?) and appropriateness. Many links in this post go to draft documents on my GitHub; "chucklorenz" should appear in the browser address bar. If the decision is made to proceed with these changes, links will be updated before committing content to the Adapt repos.

**Comment by johnniezen** [comment]
I wonder what happens if you have installed according to the Vagrant setup, and decide to start running the application from a terminal window. In Vagrant, admin is used to login, in the manual procedure you have to create your "super user". I must admit that I did not install with Vagrant, but I do think there need to be some sync here or am I totally thinking the wrong way?
The split in the procedures is really good. Well structured, and clear.

I know some basic "programming" knowledge is required, so you know what a terminal is, and working with the command line. But I think some remarks about the required versions (Git, Nvm, Mongo etc) and what happens if they need updating would be in place.
You do not want to give the impression that by trial and error the tool should start working. An update test should also be part of the documentation and have a process somewhere.
